var stimlist=(function(){function getRandomInt(min,max){return Math.floor(Math.random()*(max-min+1))+min;}
function randstr(chstr,minum,maxnum){var maxnum=(typeof maxnum==='undefined')?minum:maxnum;var nc_rand=getRandomInt(minum,maxnum);var rc='';var nstr=chstr.length;var inichstr=chstr;while(rc.length<nc_rand){var ir=getRandomInt(0,chstr.length-1);rc=rc+chstr[ir];if(chstr.length>1){chstr=chstr.replace(chstr[ir],'');}else{chstr=inichstr;}}
return rc;}
function removechars(inistr,rmchars){var torem=new RegExp('['+rmchars+']','g');var newstr=inistr.replace(torem,"");return newstr;}
function shuffle(str){var a=str.split(""),n=a.length;for(var i=n-1;i>0;i--){var j=Math.floor(Math.random()*(i+1));var tmp=a[i];a[i]=a[j];a[j]=tmp;}
return a.join("");}
var core={};core.init=function(nchar){var nch=parseInt(nchar);var vow='AEIOU';var cons='BCDFGHJKLMNPQRSTVWXZ';var allchar=vow+cons;if(nch>=100){var rlist=getRandomInt(1,6);switch(rlist){case 1:var styp='A';var seq=randstr(vow,3);var filler=cons;var name=styp+'_'+seq;break;case 2:var styp='B';var seq=randstr(cons,3);var filler=removechars(cons,seq)+vow;var name=styp+'_'+seq;break;case 3:var styp='Bp';var svow=randstr(vow,1,2);var scon=randstr(cons,3-svow.length);var seq=shuffle(svow+scon);var filler=removechars(allchar,seq);var name=styp+'_'+seq;break;case 4:var styp='C';var seq_a=randstr(vow,2);var seq_b=randstr(cons,2);var seq=[seq_a,seq_b];var filler=removechars(allchar,seq_a+seq_b);var name=styp+'_'+seq_a+seq_b;break;case 5:var ns=getRandomInt(1,5);switch(ns){case 1:var styp='Cp1';var seq_a=randstr(cons,2);var seq_b=randstr(removechars(cons,seq_a),2);break;case 2:var styp='Cp2';var seq_a=randstr(vow,2);var seq_b=randstr(removechars(vow,seq_a),2);break;case 3:var styp='Cp3';var seq_a=shuffle(randstr(vow,1)+randstr(cons,1));var seq_b=randstr(removechars(cons,seq_a),2);break;case 4:var styp='Cp3';var seq_a=shuffle(randstr(vow,1)+randstr(cons,1));var seq_b=randstr(removechars(vow,seq_a),2);break;case 5:var styp='Cp4';var seq_a=shuffle(randstr(vow,1)+randstr(cons,1));var seq_b=shuffle(randstr(removechars(vow,seq_a),1)+randstr(removechars(cons,seq_a),1));break;}
var seq=[seq_a,seq_b];var filler=removechars(allchar,seq_a+seq_b);var name=styp+'_'+seq_a+seq_b;break;case 6:var styp='D';var seq=randstr(vow,2);var filler=cons;var name=styp+'_'+seq[0]+'x'+seq[1];}}else{var styp='R';var filler=randstr(allchar+'Y',nch);var seq='';var name=styp;}
return{nchar:nch,type:styp,seq:seq,filler:filler,idname:name};};core.make=function(nchar){var listparam=core.init(nchar);var listyp=listparam.type[0];var nch=listparam.nchar;var id=listparam.idname;var filler=(typeof listparam.filler==='undefined')?"":listparam.filler;var seq=(typeof listparam.seq==='undefined')?"":listparam.seq;if(listyp=='A'||listyp=='B'){var the_list=randstr(filler,1,3);var ns=the_list.length;while(ns<nch){if(ns<nch-5){the_list=the_list+seq+randstr(filler,1,3);}else if((ns>=nch-5)&&(ns<nch-3)){the_list=the_list+seq;}else if((ns>=nch-3)&&(ns<nch)){the_list=the_list+randstr(filler,nch-ns,nch-ns);}
ns=the_list.length;}}else if(listyp=='C'){var the_list=randstr(filler,1,2);var ns=the_list.length;while(ns<nch){var the_seq=seq[getRandomInt(0,1)];if(ns<nch-4){the_list=the_list+the_seq+randstr(filler,1,2);}else if((ns>=nch-4)&&(ns<nch-2)){the_list=the_list+the_seq+randstr(filler,nch-ns-2,nch-ns-2);}else if(ns==nch-2){the_list=the_list+the_seq;}else if(ns==nch-1){the_list=the_list+randstr(filler,nch-ns,nch-ns);}
ns=the_list.length;}}else if(listyp=='D'){var the_list=randstr(filler,2,3);var ns=the_list.length;while(ns<nch){var the_seq=seq[0]+randstr(filler,1)+seq[1];if(ns<nch-5){the_list=the_list+the_seq+randstr(filler,2,3);}else if(ns==nch-8){the_list=the_list+the_seq+randstr(filler,2,2);}else if((ns>=nch-5)&&(ns<nch-2)){the_list=the_list+the_seq;}else if((ns>=nch-2)&&(ns<nch)){the_list=the_list+randstr(filler,nch-ns,nch-ns);}
ns=the_list.length;}}else if(listyp=='R'){var the_list=filler;}
return{charlist:the_list,idname:id}};return core;})();